services:
  api:
    build:
      dockerfile: Dockerfile.api
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthz"]
      interval: 10s
      timeout: 5s
      retries: 15
  springapp:
    build:
      dockerfile: Dockerfile.springapp
    ports:
      - "8080:8080"
    environment:
      API_URL: "http://api:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 15
    depends_on:
      api:
        condition: service_healthy
