version: '3.8'
services:
  springapp:
    build:
      context: ./spring-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthz"]
      interval: 10s
      timeout: 5s
      retries: 15
    depends_on:
      api:
        condition: service_healthy
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthz"]
      interval: 10s
      timeout: 5s
      retries: 15

